apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "biznavi5.fullname" . }}
  labels:
    app: {{ template "biznavi5.name" . }}
    chart: {{ template "biznavi5.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "biznavi5.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "biznavi5.name" . }}
        chart: {{ template "biznavi5.chart" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ template "biznavi5.fullname" . }}
        image: {{ template "biznavi5.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        env:
        - name: POSTGRESQL_HOST
          value: {{ template "biznavi5.postgresql.fullname" . }}
        - name: POSTGRES_USER
          value: {{ default "biznavi" .Values.postgresUser | quote }}
        - name: POSTGRESQL_PORT_NUMBER
          value: "5432"
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "biznavi5.postgresql.fullname" . }}
              key: postgres-password
        - name: BIZNAVI_USERNAME
          value: {{ .Values.biznaviUsername | quote }}
        - name: BIZNAVI_EMAIL
          value: {{ .Values.biznaviEmail | quote }}
        - name: BIZNAVI_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "biznavi5.fullname" . }}
              key: biznavi-password
        {{- if .Values.smtpHost }}
        - name: SMTP_HOST
          value: {{ .Values.smtpHost | quote }}
        {{- end }}
        {{- if .Values.smtpPort }}
        - name: SMTP_PORT
          value: {{ .Values.smtpPort | quote }}
        {{- end }}
        {{- if .Values.smtpUser }}
        - name: SMTP_USER
          value: {{ .Values.smtpUser | quote }}
        {{- end }}
        {{- if .Values.smtpPassword }}
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ template "biznavi5.fullname" . }}
              key: smtp-password
        {{- end }}
        {{- if .Values.smtpProtocol }}
        - name: SMTP_PROTOCOL
          value: {{ .Values.smtpProtocol | quote }}
        {{- end }}
        ports:
        - name: web
          containerPort: 8069
        - name: longpool
          containerPort: 8071
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}  
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: biznavi-data
          mountPath: /opt/biznavi/data
      volumes:
      - name: biznavi-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "biznavi5.fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end }}
