apiVersion: v1
kind: Secret
metadata: 
  name: {{ template "biznavi5.fullname" . }}
  labels:
    app: {{ template "biznavi5.name" . }}
    chart: {{ template "biznavi5.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
  type: Opaque
  data:
    {{ if .Values.biznaviPassword }}
    biznavi-password: {{ .Values.biznaviPassword | b64enc | quote }}
    {{ else }}
    biznavi-password: {{ randAlphaNum 10 | b64enc | quote }}
    {{ end }}
    {{ if .Values.smtpPassword }}
    smtp-password: {{ .Values.smtpPassword | b64enc | quote }}
    {{ end }}
